@echo off

REM echo rexec %UPTIME_PASSWORD% %UPTIME_REMOTE_SCRIPT% %UPTIME_POOL% | nc %UPTIME_HOSTNAME% %UPTIME_PORT%

..\..\..\apache\php\php.exe rcs.php -h=%UPTIME_HOSTNAME% -p=%UPTIME_PORT% -s=%UPTIME_PASSWORD% -c=%UPTIME_REMOTE_SCRIPT% -a=%UPTIME_POOL%
